name: GitHub Project Bot

on:
  repository_dispatch:
    types: [labeler_workflow_completed]
  workflow_dispatch: # Allows manual trigger if needed

jobs:
  update-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Handle Repo1
      uses: subhamX/github-project-bot@v1.0.0
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        COLUMN_NAME: In Progress
        PROJECT_URL: https://github.com/orgs/ORG_NAME/projects/1 
        REPO_URL: https://github.com/ORG_NAME/repo1

    - name: Handle Repo2
      uses: subhamX/github-project-bot@v1.0.0
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        COLUMN_NAME: In Progress
        PROJECT_URL: https://github.com/orgs/ORG_NAME/projects/1
        REPO_URL: https://github.com/ORG_NAME/repo2

    - name: Trigger Update Roadmap Workflow
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'update_roadmap.yml', # Assuming this is the correct filename of the workflow
            ref: context.ref
          })
